# Generated by Django 4.2.4 on 2023-08-19 10:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10000, verbose_name='Название праздника')),
                ('explanation', models.TextField(verbose_name='Описание праздника')),
                ('mainImage', models.ImageField(upload_to='', verbose_name='Главное изображение')),
                ('images', models.FileField(blank=True, upload_to='')),
                ('price', models.IntegerField(verbose_name='Цена')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10000, verbose_name='Название товара')),
                ('explanation', models.TextField(verbose_name='Описание товара')),
                ('mainImage', models.ImageField(upload_to='', verbose_name='Главное изображение')),
                ('images', models.FileField(blank=True, upload_to='')),
                ('price', models.IntegerField(verbose_name='Цена')),
                ('event', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.event', verbose_name='Зависимость к празднику')),
            ],
        ),
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='static/images/ProductEventImages/', verbose_name='Картинки')),
                ('post', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='app.product')),
            ],
        ),
        migrations.CreateModel(
            name='EventImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='static/images/EventImages/', verbose_name='Картинки')),
                ('post', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='app.event')),
            ],
        ),
    ]
