# Generated by Django 4.0.4 on 2023-08-23 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coruselimage',
            name='image',
            field=models.ImageField(blank=True, upload_to='../static/images/CoruselImages/', verbose_name='Картинки в карусель'),
        ),
        migrations.AlterField(
            model_name='event',
            name='mainImage',
            field=models.ImageField(upload_to='../static/images/EventImages/', verbose_name='Главное изображение'),
        ),
        migrations.AlterField(
            model_name='eventimage',
            name='image',
            field=models.ImageField(blank=True, upload_to='../static/images/EventImages/', verbose_name='Картинки'),
        ),
        migrations.AlterField(
            model_name='product',
            name='mainImage',
            field=models.ImageField(upload_to='../static/images/ProductEventImages/', verbose_name='Главное изображение'),
        ),
        migrations.AlterField(
            model_name='productimage',
            name='image',
            field=models.ImageField(blank=True, upload_to='../static/images/ProductEventImages/', verbose_name='Картинки'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='descriptionmImage',
            field=models.ImageField(blank=True, upload_to='../static/images/', verbose_name='Изображение в поле (О нас)'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='logoImage',
            field=models.ImageField(blank=True, upload_to='../static/images/', verbose_name='Логотип'),
        ),
    ]
