# Generated by Django 4.2.4 on 2023-08-20 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coruselimage',
            name='image',
            field=models.ImageField(blank=True, upload_to='app/static/images/CoruselImages/', verbose_name='Картинки в карусель'),
        ),
        migrations.AlterField(
            model_name='eventimage',
            name='image',
            field=models.ImageField(blank=True, upload_to='app/static/images/EventImages/', verbose_name='Картинки'),
        ),
        migrations.AlterField(
            model_name='productimage',
            name='image',
            field=models.ImageField(blank=True, upload_to='app/static/images/ProductEventImages/', verbose_name='Картинки'),
        ),
    ]
