# Generated by Django 4.0.4 on 2023-08-23 19:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_coruselimage_image_alter_event_mainimage_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coruselimage',
            name='event',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.event', verbose_name='Зависимость к празднику'),
        ),
    ]
