# Generated by Django 4.0.4 on 2023-08-25 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_coruselimage_event'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='rate_sum',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='event',
            name='rating',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='event',
            name='vote_sum',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='product',
            name='rate_sum',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='product',
            name='rating',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='product',
            name='vote_sum',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='coruselimage',
            name='image',
            field=models.ImageField(blank=True, upload_to='app/static/images/CoruselImages/', verbose_name='Картинки в карусель'),
        ),
        migrations.AlterField(
            model_name='event',
            name='mainImage',
            field=models.ImageField(upload_to='app/static/images/EventImages/', verbose_name='Главное изображение'),
        ),
        migrations.AlterField(
            model_name='eventimage',
            name='image',
            field=models.ImageField(blank=True, upload_to='app/static/images/EventImages/', verbose_name='Картинки'),
        ),
        migrations.AlterField(
            model_name='product',
            name='mainImage',
            field=models.ImageField(upload_to='app/static/images/ProductEventImages/', verbose_name='Главное изображение'),
        ),
        migrations.AlterField(
            model_name='productimage',
            name='image',
            field=models.ImageField(blank=True, upload_to='app/static/images/ProductEventImages/', verbose_name='Картинки'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='descriptionmImage',
            field=models.ImageField(blank=True, upload_to='app/static/images/', verbose_name='Изображение в поле (О нас)'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='logoImage',
            field=models.ImageField(blank=True, upload_to='app/static/images/', verbose_name='Логотип'),
        ),
    ]
