# Generated by Django 4.0.4 on 2023-08-26 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_event_avalible_product_avalible_alter_event_rate_sum_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commentsevent',
            name='comentator',
            field=models.TextField(blank=True, default='', verbose_name='Имя покупателя'),
        ),
        migrations.AlterField(
            model_name='commentsproduct',
            name='comentator',
            field=models.TextField(blank=True, default='', verbose_name='Имя покупателя'),
        ),
    ]
